apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:latest
        command: ["echo", "Hello, World!"]