apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: parallel-conditional-loop
  namespace: argo
spec:
  entrypoint: main

  arguments:
    parameters:
    - name: task-a-status
      value: "NG"  # 默认值为 "NG"，可以传入 "OK" 使 Task A 成功

  templates:
  - name: main
    dag:
      tasks:
      - name: task-a
        template: status-task
        arguments:
          parameters:
          - name: status
            value: "{{workflow.parameters.task-a-status}}"

      - name: task-b
        template: echo
        arguments:
          parameters: [{name: message, value: "Task B"}]

      - name: loop-task
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: ["task-1", "task-2", "task-3"]
        dependencies: ["task-a", "task-b"]
        when: "'{{tasks.task-a.status}}' == 'Succeeded' && '{{tasks.task-b.status}}' == 'Succeeded'"

      - name: task-c
        template: echo
        arguments:
          parameters: [{name: message, value: "Task C - Handling Failure"}]
        dependencies: ["task-a", "task-b"]
        when: "'{{tasks.task-a.status}}' != 'Succeeded' || '{{tasks.task-b.status}}' != 'Succeeded'"

  - name: status-task
    inputs:
      parameters:
      - name: status
    container:
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - |
          if [ "{{inputs.parameters.status}}" = "OK" ]; then
            echo "Task A succeeded";
            exit 0;
          else
            echo "Task A failed";
            exit 1;
          fi

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - "echo '{{inputs.parameters.message}}'"
