version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-book-store
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: book-store
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
