version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:24
    resource_class: medium

jobs:
#  test-book-store:
#    executor: python-executor
#    steps:
#      - checkout
#      - run:
#          name: Install dependencies (book-store)
#          command: |
#            cd ~/project/app/backend/book-store
#            pwd
#            ls -alt

  approve:
    executor: python-executor
    steps:
      - run:
          name: Await manual approval
          command: echo "Waiting for approval"

  build-and-push-book-store:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image (book-store)
          command: |
            cd ~/project/app/backend/book-store
            docker build -t zengemily79/book-store:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image (book-store)
          command: |
            docker push zengemily79/book-store:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - approve:
          type: approval
      - build-and-push-book-store:
          requires:
            - approve
