version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Dummy build step
          command:

  approve-to-push-image:
    executor: docker-executor
    steps:
      - run:
          name: Manual approval before push image
          command: echo "Manual approval to push image"

  push-image:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Dummy Image Build and Push
          command: echo "Build and push Docker image placeholder"

  approve-to-create-release-branch:
    executor: docker-executor
    steps:
      - run:
          name: Manual approval before releasing
          command: echo "Manual approval to release required"

  create-release-branch:
    executor: docker-executor
    environment:
      VERSION_FILE: app/backend/book-store/version.txt
    steps:
      - checkout

      - run:
          name: Install bump2version
          command: |
            pip install bump2version

      - run:
          name: Get release version (strip -SNAPSHOT)
          command: |
            VERSION=$(<"$VERSION_FILE")
            RELEASE_VERSION="${VERSION%-SNAPSHOT}"
            
            echo "export VERSION=$VERSION" >> "$BASH_ENV"
            echo "export RELEASE_VERSION=$RELEASE_VERSION" >> "$BASH_ENV"

      - run:
          name: Configure Git user and remote
          command: |
            source "$BASH_ENV"
      
            git config user.email "ci@example.com"
            git config user.name "CircleCI"
            git remote set-url origin https://${GIT_AUTH_TOKEN}@github.com/emilyzeng1977/book-store.git

      - run:
          name: Checkout release branch from develop
          command: |
            git fetch origin
            git checkout -b release/$RELEASE_VERSION origin/develop

      - run:
          name: Bump version and push release branch
          command: |
            bump2version --current-version $VERSION --new-version ${RELEASE_VERSION}-RC patch --verbose
            git commit -am "chore: bump version to ${RELEASE_VERSION}-RC"
            git push origin release/$RELEASE_VERSION

workflows:
  version: 2
  release-flow:
    jobs:
      - build # build 不限制分支，任何分支都会跑
      - approve-to-push-image:
          type: approval
      - push-image:
          requires:
            - build
            - approve-to-push-image
      - approve-to-create-release-branch:
          type: approval
      - create-release-branch:
          requires:
            - approve-on-develop
          filters:
            branches:
              only:
                - develop
