version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.12

  docker-executor:
    docker:
      - image: docker:24
    resource_class: medium

jobs:
  test-book-store:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies (book-store)
          command: |
            pwd
            ls -alt
      - run:
          name: Run tests (book-store)
          working_directory: ~/book-store
          command: |
            ls -alt
            pytest || exit 1

  approve:
    executor: python-executor
    steps:
      - run:
          name: Await manual approval
          command: echo "Waiting for approval"

  build-and-push-book-store:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image (book-store)
          working_directory: ~/book-store
          command: |
            docker build -t zengemily79/book-store:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image (book-store)
          command: |
            docker push zengemily79/book-store:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-book-store
      - approve:
          type: approval
          requires:
            - test-book-store
      - build-and-push-book-store:
          requires:
            - approve
