version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:24
    resource_class: medium

jobs:
  approve:
    executor: docker-executor
    steps:
      - run:
          name: Await manual approval
          command: echo "Waiting for approval"

  build-and-push-book-store:
    executor: docker-executor
    environment:
      PROJECT_DIR: /root/project/app/backend/book-store
      VERSION_FILE: /root/project/app/backend/book-store/version.txt
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Environment
          command: |
            cd $PROJECT_DIR
            BRANCH_NAME=$(echo "$CIRCLE_BRANCH" | sed 's/\//-/g')
            if [ "$BRANCH_NAME" != "develop" ] || [ "$BRANCH_NAME" != "main" ]; then
              VERSION=$BRANCH_NAME
              echo $VERSION > $VERSION_FILE
            fi
      - run:
          name: Build Docker Image (book-store)
          command: |
            cd $PROJECT_DIR
            VERSION=$(cat $VERSION_FILE)
            docker build -t zengemily79/book-store:$VERSION .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image (book-store)
          command: |
            cd $PROJECT_DIR
            VERSION=$(cat $VERSION_FILE)
            docker push zengemily79/book-store:$VERSION

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - approve:
          type: approval
      - build-and-push-book-store:
          requires:
            - approve
