version: 2.1

jobs:
  build:
    docker:
      - image: python:3.12  # 使用 Python 3.12 镜像
    steps:
      - checkout  # 拉取代码
      - run:
          name: 模拟构建
          command: echo "正在构建 Docker 镜像..."
      - run:
          name: 模拟打标签
          command: echo "将镜像标记为 myrepo/myapp:latest"
      - run:
          name: 模拟推送
          command: echo "将镜像推送到 Docker 仓库..."

workflows:
  version: 2
  build_and_push:
    jobs:
      - build