version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.12
    working_directory: ~/project/app/backend

  docker-executor:
    docker:
      - image: docker:24
    working_directory: ~/project/app/backend
    resource_class: medium

jobs:
  test-book-store:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies (book-store)
          working_directory: ~/project/app/backend/book-store
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests (book-store)
          working_directory: ~/project/app/backend/book-store
          command: |
            pytest || exit 1

  test-book-store-price:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies (book-store-price)
          working_directory: ~/project/app/backend/book-store-price
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests (book-store-price)
          working_directory: ~/project/app/backend/book-store-price
          command: |
            pytest || exit 1

  approve:
    executor: python-executor
    steps:
      - run:
          name: Await manual approval
          command: echo "Waiting for approval"

  build-and-push-book-store:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image (book-store)
          working_directory: ~/project/app/backend/book-store
          command: |
            docker build -t your-dockerhub-username/book-store:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image (book-store)
          command: |
            docker push your-dockerhub-username/book-store:latest

  build-and-push-book-store-price:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image (book-store-price)
          working_directory: ~/project/app/backend/book-store-price
          command: |
            docker build -t your-dockerhub-username/book-store-price:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image (book-store-price)
          command: |
            docker push your-dockerhub-username/book-store-price:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-book-store
      - test-book-store-price
      - approve:
          type: approval
          requires:
            - test-book-store
            - test-book-store-price
      - build-and-push-book-store:
          requires:
            - approve
      - build-and-push-book-store-price:
          requires:
            - approve
