version: 2.1  # 指定 CircleCI 配置的版本

jobs:  # 定义任务
  build:
    docker:
      - image: node:18  # 运行环境（Docker 镜像）
    steps:
      - checkout  # 拉取代码
      - run: npm install  # 安装依赖
      - run: npm test  # 运行测试

workflows:  # 定义工作流
  version: 2
  build_and_test:
    jobs:
      - build  # 执行 `build` 任务