version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  approve-on-develop:
    executor: docker-executor
    steps:
      - run:
          name: Manual approval before releasing
          command: echo "Manual approval to release required"

  create-release-branch-and-bump:
    executor: docker-executor
    environment:
      VERSION_FILE: app/backend/book-store/version.txt
    steps:
      - checkout

      - run:
          name: Install bump2version
          command: |
            pip install bump2version

      - run:
          name: Get release version (strip -SNAPSHOT)
          command: |
            RELEASE_VERSION=$(sed 's/-SNAPSHOT//' $VERSION_FILE)
            echo "export VERSION=$(cat $VERSION_FILE)" >> $BASH_ENV
            echo "export RELEASE_VERSION=$RELEASE_VERSION" >> "$BASH_ENV"

      - run:
          name: Configure Git and bump version
          command: |
            source "$BASH_ENV"

            # Setup Git config
            git config user.email "ci@example.com"
            git config user.name "CircleCI"

            # Override remote with token authentication
            git remote set-url origin https://${GIT_AUTH_TOKEN}@github.com/emilyzeng1977/book-store.git

            git fetch origin
            git checkout -b release/$RELEASE_VERSION origin/develop

            bump2version --current-version $VERSION --new-version ${RELEASE_VERSION}-RC patch --verbose

            git commit -am "chore: bump version to ${RELEASE_VERSION}-RC"
            git push origin release/$RELEASE_VERSION

workflows:
  version: 2
  release-flow:
    jobs:
      - approve-on-develop:
          type: approval
      - create-release-branch-and-bump:
          requires:
            - approve-on-develop
