apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store-no-db
  labels:
    app: book-store-no-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-store-no-db
  template:
    metadata:
      labels:
        app: book-store-no-db
    spec:
      containers:
      - name: book-store-no-db
        image: zengemily79/book_store_no_db:latest
        ports:
        - containerPort: 5000
        env:
        - name: HELLO_SERVER
          value: "hello"
        - name: HELLO_PORT
          value: "5000"
        - name: HELLO_URI
          value: "/hello"