#apiVersion: networking.istio.io/v1alpha3
#kind: EnvoyFilter
#metadata:
#  name: dynamic-host-routing
#  namespace: istio-system
#spec:
#  workloadSelector:
#    labels:
#      app: book-store-no-db
#  configPatches:
#    - applyTo: HTTP_FILTER
#      match:
#        context: SIDECAR_INBOUND
#      patch:
#        operation: INSERT_BEFORE
#        value:
#          name: envoy.filters.http.lua
#          typed_config:
#            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
#            inline_code: |
#              function envoy_on_request(request_handle)
#                request_handle:logInfo("new host ?????? ")
#              end