apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-ratelimit
spec:
  workloadSelector:
    labels:
      app: book-store-price # 作用于 app: book-store-price 的工作负载
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND # 针对入站流量
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit # 本地限流过滤器
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: http_local_rate_limiter # 统计前缀
            token_bucket:
              max_tokens: 1 # 最大允许1次请求
              tokens_per_fill: 1 # 每次补充1个令牌
              fill_interval: 1s # 每1秒补充一次