# 如果你需要为 Filebeat 授权以访问 Kubernetes 元数据，
# 则需要创建一个 ServiceAccount 和 RBAC（角色访问控制）设置。
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: filebeat
#  namespace: kube-system
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: filebeat
#subjects:
#  - kind: ServiceAccount
#    name: filebeat
#    namespace: kube-system
#roleRef:
#  kind: ClusterRole
#  name: cluster-admin
#  apiGroup: rbac.authorization.k8s.io
---
# 创建一个 ConfigMap 来定义 Filebeat 的配置文件
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/bookstore-deployment-*.log
    output.logstash:
      hosts: ["logstash-service.default.svc.cluster.local:5044"]

    # 可选：设置日志级别
#    logging.level: debug
---
# Filebeat 作为 DaemonSet 部署在 Kubernetes 中。
# 这样可以确保每个节点上都有一个 Filebeat 实例来收集日志。
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
#      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.7.0-arm64
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
