apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: book-store-price-http-error
spec:
  selector:
    labelSelectors:
      http: error
  mode: all
  target: Response
  replace:
    code: 500
  method: GET
  port: 5000
  path: /price