apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # 选择与 Deployment 中相同的标签
  ports:
  - port: 27017  # Service 监听的端口
    targetPort: 27017  # 容器内部的端口
  type: ClusterIP  # 仅在集群内部暴露
