apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-controller-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["chaos-mesh.org"]
    resources: ["chaosengines", "chaosexperiments", "chaosresults"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-controller-manager
subjects:
  - kind: ServiceAccount
    name: chaos-mesh-controller-manager
    namespace: chaos-testing
roleRef:
  kind: ClusterRole
  name: chaos-mesh-controller-manager
  apiGroup: rbac.authorization.k8s.io
