apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-demo
  labels:
    app: monitor-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-demo
  template:
    metadata:
      labels:
        app: monitor-demo
    spec:
      containers:
      - name: monitor-demo
        image: zengemily79/monitor-demo:latest
        ports:
        - containerPort: 5000
        env:
        - name: OTEL_COLLECTOR_URL
          value: "http://opentelemetry-collector.tracing.svc.cluster.local:4317"