apiVersion: v1
kind: Service
metadata:
  name: monitor-demo
  labels:
    app: monitor-demo
spec:
  selector:
    app: monitor-demo  # 选择与 Deployment 中相同的标签
  ports:
    - name: http-port  # 给端口指定一个名称
      port: 5000  # 服务的端口
      targetPort: 5000  # 容器的目标端口
  type: ClusterIP  # 设置为 ClusterIP 以仅在集群内部暴露
