apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-service
spec:
  hosts:
  - hello
  gateways:
  - mesh
  http:
  - match:
    - port: 5000  # 匹配来自 5000 端口的请求
      uri:
        prefix: /api/hello
    rewrite:
      uri: /hello
    route:
    - destination:
        host: hello
        port:
          number: 5000  # 转发到目标服务的 5000 端口