name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
      - '**'  # 捕获所有分支，处理其他分支

jobs:
  # 生成镜像并推送
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image version tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" || "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "This is a protected branch, approval is needed"
            echo "needs-approval=true" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')
            echo "IMAGE_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
            echo "needs-approval=false" >> $GITHUB_ENV
          fi

      - name: Wait for approval (for main and develop branches)
        if: env.needs-approval == 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          cd app/backend/book-store
          docker build -t zengemily79/book_store:${{ env.IMAGE_TAG }} .

      - name: Push image
        run: |
          docker push zengemily79/book_store:${{ env.IMAGE_TAG }}

  # 其他操作或步骤（如果有）
