name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - '**'  # 捕获所有分支的 PR

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image version tag
        id: version
        run: |
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | sed 's/\//_/g')
          echo "IMAGE_TAG=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Wait for approval (for all branches)
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          cd app/backend/book-store
          docker build -t zengemily79/book_store:${{ env.IMAGE_TAG }} .

      - name: Push image
        run: |
          docker push zengemily79/book_store:${{ env.IMAGE_TAG }}
