apiVersion: v1
kind: Service
metadata:
  name: book-store
spec:
  selector:
    app: book-store  # 选择与 Deployment 中相同的标签
  ports:
  - port: 5000  # Service 监听的端口
    targetPort: 5000  # 容器内部的端口
  type: ClusterIP  # 设置为 ClusterIP 以仅在集群内部暴露
